url: "https://susanjsp.dev/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Susan's Portfolio" # the name of your site, e.g. ACME Corp.
permalink: /projects/:title

title_image: "https://res.cloudinary.com/susanjsp/image/upload/v1611760039/portfolio/twitter-card_t5h9iz.png"

defaults:
  -
    scope:
      path: "projects" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "project-page"

twitter_username: "@susanjsp_"
author: "susanjsp"
twitter: "http://www.twitter.com/susanjsp_"
github:  "http://github.com/susanjsp"
codepen: "https://codepen.io/susanjsp"
linkedin: "https://www.linkedin.com/in/susanpan96/"
blog: "https://susanjsp.com"
email: "susanjsp@protonmail.com"

exclude:
  - .jekyll-cache